<?php

$viagem = [
    [
        "promocao"=>"promoção",
        "preco"=>3599,
        "nome"=>"Salvador",
        "foto"=>"imagem/img2.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>3999,
        "nome"=>"Ilhéus",
        "foto"=>"imagem/img3.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>2000,
        "nome"=>"Rio de Contas",
        "foto"=>"imagem/img4.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>2300,
        "nome"=>"Valença",
        "foto"=>"imagem/img5.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>1400,
        "nome"=>"Feira de Santana",
        "foto"=>"imagem/img12.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>1400,
        "nome"=>"Guanambi",
        "foto"=>"imagem/img11.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>2000,
        "nome"=>"Bom Jesus da Lapa",
        "foto"=>"imagem/imagen8.jpg" 
    ],
    [
    "promocao"=>"promoção",
    "preco"=>5000,
    "nome"=>"Porto Seguro",
    "foto"=>"imagem/img1.jpg"
    ],
    [
        "promocao"=>"promoção",
        "preco"=>1400,
        "nome"=>"Itabuna",
        "foto"=>"imagem/img9.jpg"
        ],
    [
     "promocao"=>"promoção",
     "preco"=>1600,
     "nome"=>"Vitória da Conquista",
     "foto"=>"imagem/img10.jpg"
      ],
      [
        "promocao"=>"promoção",
        "preco"=>1600,
        "nome"=>"Barreiras",
        "foto"=>"imagem/img13.jpg"
         ],
      [
            "promocao"=>"promoção",
            "preco"=>1400,
            "nome"=>"Camaçari",
            "foto"=>"imagem/img14.jpg"
       ],
       [
        "promocao"=>"promoção",
        "preco"=>1700,
        "nome"=>"Jacobina",
        "foto"=>"imagem/img15.jpg"
         ],
         [
            "promocao"=>"promoção",
            "preco"=>1600,
            "nome"=>"Alagoinhas",
            "foto"=>"imagem/img16.jpg"
             ],
             [
                "promocao"=>"promoção",
                "preco"=>2000,
                "nome"=>"Senhor do Bonfim",
                "foto"=>"imagem/img17.jpg"
                 ],
    ];